-- Profiles table
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  nickname text unique not null,
  major text not null,
  student_id text not null,
  avatar_url text,
  bio text,
  manner_temperature numeric default 36.5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Posts table
create table posts (
  id bigint generated by default as identity primary key,
  author_id uuid references profiles(id) on delete cascade not null,
  category text not null, -- 'sports', 'contest', 'study'
  title text not null,
  content text not null,
  capacity integer not null,
  deadline timestamp with time zone not null,
  status text default 'open', -- 'open', 'closed'
  tags text[],
  -- category specific fields can be stored in a jsonb or separate columns
  details jsonb, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Applications table
create table applications (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  applicant_id uuid references profiles(id) on delete cascade not null,
  status text default 'pending', -- 'pending', 'accepted', 'rejected'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(post_id, applicant_id)
);
